"""Generate WeAct GFX fonts from FreeSans Bold or a local Chicago TTF. Requires Pillow.

Source: https://ftp.gnu.org/gnu/freefont/freefont-ttf-20120503.zip
FreeSans uses the same nominal 141 DPI as Adafruit's font converter.
Chicago uses pixel sizes chosen to preserve the existing display text heights.
Example: python tools/make_weact_font.py --chicago "/path/to/Chicago v0.5.5.ttf"
"""
import argparse
from pathlib import Path
from PIL import ImageFont

ROOT = Path(__file__).resolve().parent.parent
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--chicago', type=Path, help='Path to an installed Chicago TTF; source font is not copied.')
args = parser.parse_args()
if args.chicago:
    source = args.chicago
    variants = [(9, 'small', 'ChicagoSmall'), (11, 'filament', 'ChicagoFilament'), (13, 'label', 'ChicagoLabel'),
                (round(7 * 141 / 72), 'layer', 'Chicago7pt'),
                (17, 'title', 'ChicagoTitle'), (35, 'progress', 'ChicagoProgress')]
else:
    source = ROOT / 'tools/fonts/FreeSansBold.ttf'
    variants = [(round(pt * 141 / 72), suffix, 'FreeSansBoldSmall' if suffix == 'small' else f'FreeSansBold{pt}pt')
                for pt, suffix in [(4.5, 'small'), (7, 'label'), (15, 'progress')]]
for pixels, suffix, name in variants:
    font = ImageFont.truetype(str(source), pixels)
    bitmap = []
    glyphs = []
    for code in range(32, 127):
        char = chr(code)
        mask, offset = font.getmask2(char, mode='1', anchor='ls')
        width, height = mask.size
        pixels = list(mask)
        glyphs.append((len(bitmap), width, height, round(font.getlength(char)), *offset))
        for start in range(0, len(pixels), 8):
            bitmap.append(sum((1 << (7 - i)) for i, p in enumerate(pixels[start:start + 8]) if p))
    lines = ['#pragma once', '// Generated by tools/make_weact_font.py. Do not edit.',
             f'const uint8_t {name}Bitmaps[] PROGMEM = {{']
    for start in range(0, len(bitmap), 16):
        lines.append('    ' + ', '.join(f'0x{x:02X}' for x in bitmap[start:start + 16]) + ',')
    lines += ['};', f'const GFXglyph {name}Glyphs[] PROGMEM = {{']
    lines += ['    {' + ', '.join(map(str, g)) + '},' for g in glyphs]
    lines += ['};', f'const GFXfont {name} = {{',
              f'    (uint8_t*){name}Bitmaps, (GFXglyph*){name}Glyphs,',
              f'    32, 126, {sum(font.getmetrics())}', '};', '']
    (ROOT / f'Bambu_Monitor_ESP32/font_weact_{"chicago_" if args.chicago else ""}{suffix}.h').write_text('\n'.join(lines))
